// templates.ts - predefined diet plan templates
import { DietTemplate } from '../types/dietplan.types'

export const DIET_TEMPLATES: DietTemplate[] = [
  {
    id: 'weight-loss',
    name: 'Weight Loss Plan',
    description: 'Low calorie high fiber diet for steady weight loss',
    suitableFor: ['Weight Loss'],
    meals: {
      day1: { breakfast: 'Oats with skimmed milk and banana', lunch: 'Grilled chicken with brown rice and salad', dinner: 'Vegetable soup with whole wheat bread', snacks: 'Apple and green tea' },
      day2: { breakfast: 'Boiled eggs with whole wheat toast', lunch: 'Lentil soup with brown rice', dinner: 'Grilled fish with steamed vegetables', snacks: 'Cucumber sticks with hummus' },
      day3: { breakfast: 'Greek yogurt with berries', lunch: 'Quinoa salad with chickpeas', dinner: 'Stir fried tofu with vegetables', snacks: 'Orange and handful of almonds' },
      day4: { breakfast: 'Smoothie with spinach banana and almond milk', lunch: 'Grilled chicken wrap with lettuce', dinner: 'Baked salmon with asparagus', snacks: 'Carrot sticks and green tea' },
      day5: { breakfast: 'Poha with vegetables', lunch: 'Dal with brown rice and salad', dinner: 'Grilled paneer with sauteed vegetables', snacks: 'Pear and buttermilk' },
      day6: { breakfast: 'Idli with sambar', lunch: 'Rajma with brown rice', dinner: 'Mixed vegetable curry with roti', snacks: 'Watermelon and green tea' },
      day7: { breakfast: 'Upma with vegetables', lunch: 'Chole with whole wheat roti', dinner: 'Grilled chicken with roasted vegetables', snacks: 'Banana and buttermilk' },
    },
  },
  {
    id: 'muscle-gain',
    name: 'Muscle Gain Plan',
    description: 'High protein diet to support muscle growth',
    suitableFor: ['Muscle Gain'],
    meals: {
      day1: { breakfast: 'Eggs scrambled with whole wheat toast and milk', lunch: 'Chicken breast with sweet potato and broccoli', dinner: 'Salmon with quinoa and green beans', snacks: 'Protein shake and banana' },
      day2: { breakfast: 'Greek yogurt with granola and nuts', lunch: 'Tuna sandwich with whole wheat bread', dinner: 'Beef stir fry with brown rice', snacks: 'Cottage cheese with fruit' },
      day3: { breakfast: 'Omelette with cheese and vegetables', lunch: 'Paneer tikka with roti and dal', dinner: 'Grilled chicken with mashed potato', snacks: 'Boiled eggs and nuts' },
      day4: { breakfast: 'Protein pancakes with honey', lunch: 'Chicken curry with rice', dinner: 'Fish curry with brown rice', snacks: 'Protein shake and apple' },
      day5: { breakfast: 'Milk with oats and banana', lunch: 'Mutton curry with rice', dinner: 'Grilled salmon with vegetables', snacks: 'Peanut butter toast' },
      day6: { breakfast: 'Egg bhurji with paratha', lunch: 'Chicken biryani with raita', dinner: 'Paneer with dal and roti', snacks: 'Nuts and milk' },
      day7: { breakfast: 'Smoothie with protein powder and oats', lunch: 'Grilled fish with quinoa salad', dinner: 'Chicken stew with whole wheat bread', snacks: 'Boiled eggs and banana' },
    },
  },
  {
    id: 'diabetic-friendly',
    name: 'Diabetic Friendly Plan',
    description: 'Low glycemic index foods to manage blood sugar',
    suitableFor: ['Diabetic'],
    meals: {
      day1: { breakfast: 'Steel cut oats with cinnamon and nuts', lunch: 'Grilled chicken with roasted vegetables', dinner: 'Lentil soup with small portion brown rice', snacks: 'Small apple and almonds' },
      day2: { breakfast: 'Boiled eggs with whole wheat toast', lunch: 'Mixed vegetable curry with 2 rotis', dinner: 'Grilled fish with steamed broccoli', snacks: 'Cucumber and buttermilk' },
      day3: { breakfast: 'Greek yogurt with flaxseeds', lunch: 'Dal with small portion rice and salad', dinner: 'Paneer bhurji with 2 rotis', snacks: 'Pear and walnuts' },
      day4: { breakfast: 'Vegetable upma with no sugar', lunch: 'Rajma with 2 rotis', dinner: 'Grilled chicken with sauteed spinach', snacks: 'Roasted chana and green tea' },
      day5: { breakfast: 'Idli with sambar no sugar', lunch: 'Chole with 2 rotis', dinner: 'Fish curry with small brown rice', snacks: 'Orange and almonds' },
      day6: { breakfast: 'Moong dal chilla with mint chutney', lunch: 'Grilled paneer with quinoa', dinner: 'Vegetable soup with whole wheat bread', snacks: 'Buttermilk and roasted seeds' },
      day7: { breakfast: 'Poha with vegetables no sugar', lunch: 'Chicken curry with 2 rotis', dinner: 'Stir fried tofu with vegetables', snacks: 'Apple and green tea' },
    },
  },
  {
    id: 'keto',
    name: 'Keto Plan',
    description: 'High fat low carb diet for ketosis and weight loss',
    suitableFor: ['Weight Loss', 'General Health'],
    meals: {
      day1: { breakfast: 'Eggs with avocado and cheese', lunch: 'Chicken salad with olive oil dressing', dinner: 'Grilled salmon with buttered asparagus', snacks: 'Cheese and walnuts' },
      day2: { breakfast: 'Omelette with mushrooms and cheese', lunch: 'Tuna salad with cucumber and mayo', dinner: 'Beef steak with roasted broccoli', snacks: 'Avocado and boiled eggs' },
      day3: { breakfast: 'Greek yogurt with nuts no fruit', lunch: 'Grilled chicken with spinach salad', dinner: 'Pork chops with cauliflower mash', snacks: 'Almonds and cheese' },
      day4: { breakfast: 'Scrambled eggs with smoked salmon', lunch: 'Caesar salad with grilled chicken no croutons', dinner: 'Lamb chops with roasted vegetables', snacks: 'Macadamia nuts' },
      day5: { breakfast: 'Bulletproof coffee with eggs', lunch: 'Shrimp salad with avocado', dinner: 'Grilled fish with zucchini', snacks: 'Cheese slices and olives' },
      day6: { breakfast: 'Keto pancakes with butter', lunch: 'BLT salad no bread', dinner: 'Chicken thighs with roasted cauliflower', snacks: 'Pecans and cream cheese' },
      day7: { breakfast: 'Eggs benedict no muffin', lunch: 'Cobb salad with olive oil', dinner: 'Grilled steak with buttered spinach', snacks: 'Dark chocolate and almonds' },
    },
  },
  {
    id: 'high-protein',
    name: 'High Protein Plan',
    description: 'Protein rich meals for fitness and body composition',
    suitableFor: ['Muscle Gain', 'Weight Loss'],
    meals: {
      day1: { breakfast: '6 egg whites omelette with vegetables', lunch: 'Grilled chicken breast with quinoa', dinner: 'Baked cod with sweet potato', snacks: 'Cottage cheese and nuts' },
      day2: { breakfast: 'Protein shake with oats and banana', lunch: 'Turkey wrap with whole wheat tortilla', dinner: 'Grilled salmon with brown rice', snacks: 'Hard boiled eggs' },
      day3: { breakfast: 'Greek yogurt parfait with granola', lunch: 'Chicken and black bean bowl', dinner: 'Lean beef stir fry with vegetables', snacks: 'Edamame and string cheese' },
      day4: { breakfast: 'Smoked salmon with cream cheese toast', lunch: 'Shrimp and avocado salad', dinner: 'Chicken tikka with dal', snacks: 'Protein bar and apple' },
      day5: { breakfast: 'Egg muffins with spinach and feta', lunch: 'Tuna and chickpea salad', dinner: 'Grilled chicken with lentils', snacks: 'Roasted pumpkin seeds' },
      day6: { breakfast: 'Paneer scramble with whole wheat toast', lunch: 'Chicken soup with vegetables', dinner: 'Baked tilapia with quinoa', snacks: 'Almonds and low fat cheese' },
      day7: { breakfast: 'Whey protein smoothie with berries', lunch: 'Grilled chicken with hummus wrap', dinner: 'Salmon and asparagus foil packet', snacks: 'Greek yogurt with honey' },
    },
  },
  {
    id: 'balanced',
    name: 'Balanced Diet Plan',
    description: 'Well rounded nutrition for general health and wellness',
    suitableFor: ['Maintain Weight', 'General Health'],
    meals: {
      day1: { breakfast: 'Whole grain toast with peanut butter and banana', lunch: 'Vegetable rice bowl with tofu', dinner: 'Dal tadka with roti and salad', snacks: 'Mixed fruit and nuts' },
      day2: { breakfast: 'Dosa with sambar and chutney', lunch: 'Chicken sandwich with whole wheat bread', dinner: 'Pasta with tomato sauce and vegetables', snacks: 'Yogurt and granola' },
      day3: { breakfast: 'Poha with peanuts and vegetables', lunch: 'Rajma rice with pickle', dinner: 'Grilled fish with vegetables and roti', snacks: 'Apple and almonds' },
      day4: { breakfast: 'Smoothie bowl with fruits and seeds', lunch: 'Paneer butter masala with rice', dinner: 'Chicken soup with whole wheat bread', snacks: 'Hummus with carrot sticks' },
      day5: { breakfast: 'Idli with coconut chutney', lunch: 'Mixed dal with rice and papad', dinner: 'Egg curry with roti', snacks: 'Banana and peanut butter' },
      day6: { breakfast: 'Aloo paratha with yogurt', lunch: 'Vegetable biryani with raita', dinner: 'Grilled chicken with salad', snacks: 'Dates and walnuts' },
      day7: { breakfast: 'Oats porridge with fruits', lunch: 'Palak paneer with roti', dinner: 'Fish curry with brown rice', snacks: 'Orange and pistachios' },
    },
  },
]
